### ISSUE TITLE
Automatically get latest MASTER file

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-data-normalizer#1]
Make a script or request an API to fetch the latest MASTER file, rather than checking the file into the repository manually

**Comment by gman-php** [comment]
Can you share a way how you have decoded a GAME_MASTER file to JSON? So I can use it with this repo? :) Googling for a decoded drives ma mad and I always end up in the same old Reddit threads...
Thanks!

**Comment by BrunnerLivio** [comment]
@gman-php Yes, I also always end up at the same reddit threads. :( 

I actually got the JSON-GAME_MASTER-file also from a reddit thread haha.
