### ISSUE TITLE
Replace `rm` in package.json with something cross-platform

### ISSUE THREAD

**Issue by proegssilb** [BrunnerLivio/pokemongo-data-normalizer#17]
There's multiple NPM packages that essentially do the same thing as the `rm` command, but also work on Windows. In this repo, that would enable Windows Home users to run `npm clean` without having to figure out Docker Toolbox (Docker for Windows only works on Windows 10 Pro), or even if their Docker install goes south (like mine did).

**Comment by BrunnerLivio** [comment]
I usually work on Ubuntu or Git Bash for Windows, that explains why I did not get this error. Definitely change that!
