### ISSUE TITLE
Split up *.parser.ts classes

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-data-normalizer#22]
We should split the functionality of the parsers. 

After a discussion with @proegssilb, we came to the following conclusion:

We split up the EvolutionTree as RuntimeComponent.

**RuntimeComponents** (the name can be discussed) get called inside *.parser.ts. They have the information of the whole Pokemon Array. An example for this use case is EvolutionTree. The evolution tree cant be generated, without knowing all Pokemons. 

```
components/
├── index.ts
├── move
│   ├── index.ts
│   ├── move.mapper.ts
│   ├── move.model.ts
│   ├── move.parser.ts
│   ├── move.writer.ts
│   └── shared
├── pokemon
│   ├── index.ts
│   ├── pokemon.mapper.ts
│   ├── pokemon.model.ts
│   ├── pokemon.parser.ts
│   ├── pokemon.writer.ts
│   └── **shared - Subcomponents specific for Pokemon related**
│       ├── **cp-calculator - Move in here**
│       │   ├── cp-calculator.spec.ts
│       │   ├── cp-calculator.ts
│       │   └── index.ts
│       └── **evolution-tree - Refactor into this folder**
│           ├── evolution-tree.spec.ts
│           ├── evolution-tree.ts
│           └── index.ts
└── **shared - General components which can be shared**
    └── **general-component - Example Component**
        ├── general-component.spec.ts
        ├── general-component.ts
        └── index.ts
```
Next steps:

1. Move cp-calculator into components/pokemon/shared
2. Refactor/Split up evolution tree

Experimental thoughts:

- Maybe [play with decorators](https://www.typescriptlang.org/docs/handbook/decorators.html) for the registration of a RuntimeComponents. For example:

```TypeScript
@RuntimeComponent('Pokemon')
class EvolutionTree {
     public Parse(pokemons: Pokemon[]) { }
}
```

**Comment by proegssilb** [comment]
Is this in reference to #14 , or is it broader?

**Comment by BrunnerLivio** [comment]
@proegssilb Yes it is. 
I'm referring to

BrunnerLivio:
> Maybe we should consider in the future to split up PokemonParser, but that can be done in another PR.


proegssilb: 
> Splitting up PokemonParser is definitely something I'd want to dive into a bit further (maybe in an issue or over Discord) before I worked on it. Just to make sure I understand the reasoning and goal. 

We should have a talk about this in discord how we want to structure the project in general.

**Comment by BrunnerLivio** [comment]
@proegssilb Updated the description

**Comment by BrunnerLivio** [comment]
@proegssilb I created a branch refactor/structure. Could you move the EvolutionTree functionality?

**Comment by proegssilb** [comment]
Will do. Sorry, been tied up the past ~4-5 days, that might continue.

**Comment by BrunnerLivio** [comment]
@proegssilb dont worry and no hurry :sparkles:
