### ISSUE TITLE
Add Pokemon evolve information

### ISSUE THREAD

**Issue by BrunnerLivio** [BrunnerLivio/pokemongo-data-normalizer#6]

**Comment by proegssilb** [comment]
I think the most useful form of this would be as outlined in [Biuni's pokedex](https://github.com/Biuni/PokemonGO-Pokedex). Specifically, name and number of all previous/future evolutions in a list field. That said, I see nothing wrong with next and/or prev pointers in addition to lists of evolutions. 

For my situation ([visual tiers with evolution indicators](https://github.com/proegssilb/pokemon-go-rankings)), I really would benefit a lot from the list fields.

I'll likely fork the repo and see if I can take a crack at this, but I'm not sure how much time I have to work on it.

**Comment by proegssilb** [comment]
Are you using Windows, Mac, or Linux to develop this, and what version of lodash do you have installed?

There's something going on with my machine where tsc refuses to work, complaining about WeakMap needing to be declared with identical type parameters in all places... Oh, and it blames some lodash file...

**Comment by BrunnerLivio** [comment]
@proegssilb seemed like an error from @types/lodash https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324. 
Fixed this with commit 934c02abd01bda0579c061e76dc2075c00cf349e

I developed this with Linux and Windows by the way

**Comment by BrunnerLivio** [comment]
@proegssilb really strange. In my docker container it can't find package ts-node and [Travis can't find Mocha](https://travis-ci.org/BrunnerLivio/pokemongo-data-normalizer/jobs/215824987). But when I run locally `npm cache clean && rm -rf node_modules/ && npm install && npm run start` it works.   This does not make sense for me? 
I've added both of these dependencies in the package.json. Maybe something is wrong with the npm registry.

**Comment by BrunnerLivio** [comment]
@proegssilb Fetch upstream & try again. If it does not work update npm.
