### ISSUE TITLE
Add Max CP information

### ISSUE THREAD

**Issue by proegssilb** [BrunnerLivio/pokemongo-data-normalizer#9]
Base Stats are already included in the pokemon data, so Max CP is a relatively simple calculation away. Slight change to the class PokemonMapper based on [the fine work of The Silph Road redditors](https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/), and you should be done.

**Comment by proegssilb** [comment]
The reddit thread I linked to references a "CP Multiplier". The links eventually point [here](https://github.com/mathiasbynens/pogocpm2level/blob/master/pogocpm2level/cpm2level.py), where the "exact multiplier" for Max CP at max pokemon level seems to be **0.79030001**.

OK, sure, they have an entry for level "40.5" with a multiplier of "1", but that yields some very suspicious numbers in my experimentation. I think that particular table needs some more work from someone with a highly-leveled pokemon.

**Comment by BrunnerLivio** [comment]
Thanks! I'll investigate time as soon as possible and put you as a reviewer in the PR
